### PR TITLE
Delete card

### PR DESCRIPTION
**Pull request by rueveydaakuel**
please check the delete function :)

### CODE REVIEW

**Review by actyvystom — CHANGES_REQUESTED** [review]
Well done! 👍🏻 
See some comments and suggestions to improve a few lines.
What about your Vercel deployment? There is no preview deployment attached...
Cheers, Thomas

**Comment by rueveydaakuel** [comment]
Hello Thomas, thank you for your review 😃 I have implemented your suggestions.
Vercel is linked, it's just oddly hidden, which has never been the case before.🧐
Bildschirmfoto 2023-07-04 um 11 45 00

**Review by ThysBat — APPROVED** [review]
LGTM 🚀

**Comment by actyvystom** [comment]
> Hello Thomas, thank you for your review 😃 I have implemented your suggestions. Vercel is linked, it's just oddly hidden, which has never been the case before.🧐 Bildschirmfoto 2023-07-04 um 11 45 00

Oh, my bad! 🙈

**Pull request merged**
